# Generated by Django 3.2.21 on 2023-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_nr',
            field=models.IntegerField(default=100),
        ),
    ]
