# Generated by Django 4.2.6 on 2023-12-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_auto_20231016_1241'),
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nr_of_guests', models.IntegerField()),
                ('comments', models.TextField()),
                ('allergies', models.ManyToManyField(blank=True, to='catering.allergen')),
                ('hire_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.hirepackage')),
            ],
        ),
        migrations.AddField(
            model_name='hirepackage',
            name='hires',
            field=models.ManyToManyField(blank=True, to='hire.hirerequest'),
        ),
    ]
