# Generated by Django 4.2.6 on 2023-12-04 16:49

from django.db import migrations, models
import hire.tools


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_hirerequest_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequest',
            name='date',
            field=models.DateField(validators=[hire.tools.date_validation]),
        ),
    ]
